[Config]
Dependencies=base

[Output]
Format=sysext
Overlay=yes
ImageId=ext-virt
Verity=no
CompressOutput=zstd

[Content]
Bootable=no
BaseTrees=%O/base_%v
Packages=
    qemu-system-x86
    qemu-system-arm
    libvirt-daemon-system
    libvirt-clients
    virt-manager
    bridge-utils
    virtinst
