[Config]
Dependencies=base

[Output]
Format=directory
SplitArtifacts=
CompressOutput=false

[Content]
Bootable=false
BaseTrees=
    %O/base_%v
    %O/driver-broadcom-modules-%a_%v.raw
    %O/driver-nvidia-modules-%a_%v.raw
Output=modules-db_%v
