[Config]
Dependencies=base

[Output]
Format=directory
SplitArtifacts=
ImageId=liveiso

[Content]
BaseTrees=%O/base_%v
CleanPackageMetadata=no
Bootable=yes
WithRecommends=yes
RemovePackages=
    systemd-boot
Packages=
    elementary-live
    io.elementary.installer-session
    grub-efi
    mokutil
    shim-signed
    e2fsprogs
    dosfstools
    casper
    initramfs-tools
Bootloader=grub
KernelInitrdModules=
    default
    ahci
    nvme
    xhci_pci
    usb_storage
    uas
    sd_mod
    sr_mod
    isofs
    loop
    ext4
KernelCommandLine=
    rw
    console=ttyS0
    boot=casper

[Validation]
SecureBoot=no
SignExpectedPcr=no
