[Config]
MinimumVersion=26~devel

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe,restricted

[Content]
InitrdProfiles=plymouth
InitrdVolatilePackages=
    systemd
    udev
    systemd-cryptsetup
    cryptsetup-bin
    bash
    coreutils
    util-linux
    plymouth
    plymouth-theme-elementary

[Build]
ToolsTree=default
BuildSources=%D/mkosi.cache:mkosi.cache
Incremental=yes
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=resolute

[Output]
ImageId=elementary
Format=none
