[Config]
MinimumVersion=26~devel

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe,restricted

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
Incremental=yes
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=resolute

[Output]
ImageId=elementary
OutputDirectory=mkosi.output/
Format=none
