[Config]
MinimumVersion=26~devel
Dependencies=
    base
	sysupdate
    liveiso
    ext-sdk
    ext-virt

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
Incremental=yes
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=resolute

[Output]
ImageId=elementary
OutputDirectory=mkosi.output/
Format=none
