[Match]
Architecture=arm64

[Build]
ToolsTreePackages=grub-efi-arm64-bin

[Config]
Dependencies=
    base
	sysupdate
    liveiso
    ext-sdk
    ext-virt
    driver-nvidia-addon
    driver-nvidia-modules
    driver-nvidia-runtime
    modules-db
