[Match]
Architecture=x86-64

[Build]
ToolsTreePackages=grub-efi-amd64-bin

[Config]
Dependencies=
    base
	sysupdate
    liveiso
    ext-sdk
    ext-virt
    driver-nvidia-addon
    driver-nvidia-modules
    driver-nvidia-runtime
    driver-broadcom-addon
    driver-broadcom-modules
    driver-broadcom-runtime
