#driver-nvidia
[Config]
Dependencies=base

[Output]
ImageId=driver-nvidia
Format=sysext
Overlay=yes
Output=driver-nvidia-%a_%v
CompressOutput=false

[Validation]
Verity=yes

[Build]
Environment=DEB_BUILD_PROFILES=nokerneldkms

[Content]
Bootable=no
BaseTrees=%O/base_%v
BuildPackages=
    linux-headers-generic
Packages=
    linux-modules-nvidia-610-open-generic
    libnvidia-gl-610
    nvidia-utils-610
    nvidia-driver-610-open
BuildScripts=get-module-only
