#!/bin/bash
set -euo pipefail

KVER=$(ls "$BUILDROOT/lib/modules" | head -n 1)

mkdir -p "$DESTDIR/usr/lib/modules/$KVER/updates/dkms"

cp "$BUILDROOT/lib/modules/$KVER/updates/dkms/wl.ko.zst" "$DESTDIR/usr/lib/modules/$KVER/updates/dkms/"

find "$BUILDROOT/usr/lib/modules/$KVER/" -maxdepth 1 -type f -name 'modules.*' -delete
