#broadcom-addon
[Config]
Dependencies=base

[Match]
Architecture=x86-64

[Output]
ImageId=driver-broadcom-addon
Format=addon
Overlay=yes
Output=driver-broadcom-addon-%a_%v
OutputExtension=addon.efi
CompressOutput=zstd

[Validation]
Verity=yes

[Content]
BaseTrees=%O/base_%v
Packages=systemd-boot-efi
KernelCommandLine=module_blacklist=b43,bcma,brcmsmac,brcmutil,ssb
