[Partition]
Type=root
Format=ext4
SizeMinBytes=15G
Weight=45000
MakeDirectories=/var /opt /home /var/usrlocal
CopyFiles=/var/lib/flatpak:/var/lib/flatpak
Encrypt=off
FactoryReset=yes
Label=elementary-root
