#broadcom-runtime
[Config]
Dependencies=base

[Match]
Architecture=x86-64

[Output]
ImageId=driver-broadcom-runtime
Format=sysext
Overlay=yes
Output=driver-broadcom-runtime-%a_%v
CompressOutput=zstd

[Validation]
Verity=yes

[Content]
Bootable=no
BaseTrees=%O/base_%v
RemovePackages=broadcom-sta-dkms
BuildScripts=enable-runtime.chroot
FinalizeScripts=%D/scripts/EXTENSION_RELOAD_MANAGER
Packages=
    broadcom-sta-common
