#broadcom-modules
[Config]
Dependencies=base

[Match]
Architecture=x86-64

[Output]
ImageId=driver-broadcom-modules
Format=sysext
Overlay=yes
Output=driver-broadcom-modules-%a_%v
CompressOutput=zstd

[Validation]
Verity=yes

[Content]
Bootable=no
BaseTrees=%O/base_%v
BuildPackages=
    dkms
    broadcom-sta-dkms
    linux-headers-generic
Packages=kmod
BuildScripts=get-module-only

