[Match]
Distribution=ubuntu

[Content]
RemoveFiles=
    /usr/bin/chsh
    /usr/bin/lchsh
VolatilePackages=
    systemd-container
Packages=
    apparmor
    apparmor-profiles
    apparmor-utils
    btrfs-progs
    cryptsetup
    distrobox
    curl
    git
    linux-firmware
    linux-image-generic
    lvm2
    nano
    network-manager
    pipewire-audio
    plymouth
    sudo-rs
    systemd-boot
    systemd-cryptsetup
    systemd-homed
    systemd-repart
    systemd-resolved
    systemd-zram-generator
    vim
    xz-utils
    zstd
