#! /bin/sh

set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f binary.manifest binary.manifest-desktop binary.log binary.iso.md5
rm -f livecd.*
rm -rf gnupg pool userdata
