#!/bin/sh

set -e

. ./terraform.conf

# HWE starts with y, Y or 1?
if [ "$HWE" = "yes" ]; then
    KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
    XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
else
    KERNEL_FLAVORS="generic"
fi

lb config noauto \
    --cache false \
    --bootstrap-qemu-arch "$ARCH" \
    --bootstrap-qemu-static "$QEMU_BINARY_PATH" \
    --architectures "$ARCH" \
    --mode ubuntu \
    --distribution "$BASECODENAME" \
    --parent-distribution "$BASECODENAME" \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --linux-packages linux-image \
    --linux-flavours "$KERNEL_FLAVORS" \
    --bootappend-live "boot=live" \
    --mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --mirror-binary "$MIRROR_BINARY" \
    --parent-mirror-binary "$MIRROR_BINARY" \
    --mirror-chroot-security "$SECURITY_MIRROR_URL" \
    --parent-mirror-chroot-security "$SECURITY_MIRROR_URL" \
    --mirror-binary-security "$SECURITY_MIRROR_URL" \
    --parent-mirror-binary-security "$SECURITY_MIRROR_URL" \
    --keyring-packages ubuntu-keyring \
    --apt-options "--yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100" \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --hdd-label "$NAME" \
    --firmware-binary false \
    --firmware-chroot false \
    --zsync false \
	--binary-images "$BINARY_IMAGE_FORMAT" \
	--binary-filesystem "$BINARY_FILESYSTEM" \
	--compression "$COMPRESSION" \
    "${@}"

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@CODENAME/$CODENAME/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

sed -i "s/@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install