#nvidia-runtime
[Config]
Dependencies=base
ImageId=driver-nvidia-runtime

[Output]
Format=sysext
Overlay=yes
Output=driver-nvidia-runtime-%a_%v
CompressOutput=zstd

[Validation]
Verity=yes

[Content]
Bootable=no
BaseTrees=%O/base_%v
Environment=DEB_BUILD_PROFILES=nokerneldkms
RemovePackages=linux-modules-nvidia-590-open-generic
Packages=
    libnvidia-gl-590
    nvidia-utils-590
    nvidia-driver-590-open
