#nvidia-runtime
[Config]
Dependencies=base

[Output]
ImageId=driver-nvidia-runtime
Format=sysext
Overlay=yes
Output=driver-nvidia-runtime-%a_%v
CompressOutput=false

[Validation]
Verity=yes

[Build]
Environment=DEB_BUILD_PROFILES=nokerneldkms

[Content]
Bootable=no
BaseTrees=%O/base_%v
RemovePackages=linux-modules-nvidia-590-open-generic
Packages=
    libnvidia-gl-590
    nvidia-utils-590
    nvidia-driver-590-open
