#nvidia-modules
[Config]
Dependencies=base
ImageId=driver-nvidia-modules

[Output]
Format=sysext
Overlay=yes
Output=driver-nvidia-modules-%a_%v
CompressOutput=zstd

[Validation]
Verity=yes

[Content]
Bootable=no
BaseTrees=%O/base_%v
Environment=DEB_BUILD_PROFILES=nokerneldkms
Packages=linux-modules-nvidia-590-open-generic
FinalizeScripts=depmod-nvidia
