#nvidia-modules
[Config]
Dependencies=base

[Output]
ImageId=driver-nvidia-modules
Format=sysext
Overlay=yes
Output=driver-nvidia-modules-%a_%v
CompressOutput=false

[Validation]
Verity=yes

[Build]
Environment=DEB_BUILD_PROFILES=nokerneldkms

[Content]
Bootable=no
BaseTrees=%O/base_%v
Packages=linux-modules-nvidia-590-open-generic
BuildScripts=get-module-only
