[Config]
Dependencies=base

[Match]
Distribution=ubuntu

[Output]
Format=disk
SplitArtifacts=partitions,uki
CompressOutput=zstd

[Content]
RemovePackages=
    command-not-found
VolatilePackages=
    systemd-boot-efi
Bootable=yes
BaseTrees=%O/base_%v
Output=elementary_%v
CleanPackageMetadata=yes
Bootloader=systemd-boot
KernelInitrdModules=
    default
    ahci
    nvme
    xhci_pci
    usb_storage
    uas
    sd_mod
    dm-verity
KernelCommandLine=
    splash
    quiet
    root=dissect
    mount.usr=dissect
    rw
    audit=0
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=unprotected+absent:home=unprotected+absent:=ignore
    systemd.image_filter=usr=elementary_*:usr-verity=elementary_*:usr-verity-sig=elementary_*:root=elementary-*:home=elementary-*
    ipe.enforce=0

[Validation]
SecureBoot=no
SignExpectedPcr=no
