[Match]
Distribution=ubuntu

[Output]
Format=directory
ImageId=base
SplitArtifacts=

[Content]
Bootable=no
CleanPackageMetadata=no
Packages=
    systemd-container
VolatilePackages=
    passwd
    login
    uidmap
    systemd-boot
