[Config]
Dependencies=base

[Match]
Architecture=arm64

[Output]
Format=directory
SplitArtifacts=
CompressOutput=false

[Content]
Bootable=false
BaseTrees=
    %O/base_%v
    %O/driver-nvidia-modules-%a_%v.raw
Output=modules-db_%a-%v
