name: Build and Release

on:
  workflow_call:
    inputs:
      build_type:
        description: 'Stream to build for (daily or stable)'
        required: true
        type: string

jobs:
  build-and-release:
    name: Build Image and Release
    strategy:
      matrix:
          include:
            - runner: ubuntu-26.04
              arch: amd64
            - runner: ubuntu-26.04-arm
              arch: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install just podman -y

      - name: Get arch
        run: |
          echo "ARCH=$(just _get_arch)" >> "$GITHUB_ENV"

      - name: Generate key
        run: just genkey

      - name: Build with mkosi
        # Will either run do-daily or do-stable
        run: just do-${{ inputs.build_type }}

      - name: Generate SHA256SUMS (all partitions)
        run: just checksum-repo

      - name: Import GPG Key
        run: echo "${{ secrets.SYSUPDATE_GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Extract Date
        id: get_date
        run: |
          set -euo pipefail
          FILE_PATH=$(ls mkosi.output/*.usr-*.raw.zst | head -n 1)
          TIMESTAMP=$(basename "$FILE_PATH" | grep -oE '[0-9]{14}' | head -n 1 || true)
          if [ -z "$TIMESTAMP" ]; then
            echo "Fatal: No timpestamped file found."
            exit 0
          fi
          echo "Release date: $TIMESTAMP"
          echo "RELEASE_DATE=$TIMESTAMP" >> "$GITHUB_OUTPUT"

      - name: Upload sysupdate, iso and SHA256SUMS to Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          set -euo pipefail

          R2_BUCKET_UPDATES="${{inputs.build_type}}-updates"
          R2_BUCKET_INSTALLER="${{inputs.build_type}}-installer"

          # Upload image parts
          cd mkosi.output
          find . -maxdepth 1 -type f \( \
              -name "*.efi" \
              -o -name "*.usr-*.*.raw.zst" \
              -o -name "*.usr-*-verity.*.raw.zst" \
              -o -name "*.usr-*-verity-sig.*.raw.zst" \
            \) -print0 | while IFS= read -r -d '' f; do
              aws s3 cp "$f" "s3://$R2_BUCKET_UPDATES/$ARCH/" \
                --cache-control "public, max-age=31536000, immutable"
            done
          cd ..

          # Send the current SHA as versioned SHA to the bucket
           aws s3 cp mkosi.output/SHA256SUMS \
            "s3://$R2_BUCKET_UPDATES/$ARCH/SHA256SUMS_versioned.$TIMESTAMP" \
            --content-type "text/plain" \
            --cache-control "no-cache"

          TEMP_SHAS="temp_shas"
          mkdir -p "$TEMP_SHAS"

          # Download all versioned SHA, including the one generated at last step
          aws s3 cp "s3://$R2_BUCKET_UPDATES/$ARCH/" "$TEMP_SHAS/" \
              --recursive \
              --exclude "*" \
              --include "SHA256SUMS_versioned.*"

          # Concatenate all versioned SHA to a master SHA256SUMS, required by sysupdate
          cat "$TEMP_SHAS"/SHA256SUMS_versioned.* > "$TEMP_SHAS/SHA256SUMS"

          # Sign master SHA
          gpg --batch --pinentry-mode loopback \
              --passphrase "${{ secrets.SYSUPDATE_GPG_PASS }}" \
              --local-user "sysupdate" \
              --output "$TEMP_SHAS/SHA256SUMS.gpg" \
              --detach-sign "$TEMP_SHAS/SHA256SUMS"

          # Replace master SHA in bucket
          aws s3 cp "$TEMP_SHAS/SHA256SUMS" \
            "s3://$R2_BUCKET_UPDATES/$ARCH/SHA256SUMS" \
            --content-type "text/plain" \
            --cache-control "no-cache"

          # Replace master signed SHA in bucket
          aws s3 cp "$TEMP_SHAS/SHA256SUMS.gpg" \
            "s3://$R2_BUCKET_UPDATES/$ARCH/SHA256SUMS.gpg" \
            --content-type "application/pgp-signature" \
            --cache-control "no-cache"

          # Live ISO + hash
          ISO=$(basename $(ls mkosi.output/elementaryos-*.iso | head -n 1))
          ( cd mkosi.output && sha256sum "$ISO" > "$ISO.sha256.txt" )

          aws s3 cp "mkosi.output/$ISO" "s3://$R2_BUCKET_INSTALLER/$ISO" \
            --cache-control "public, max-age=31536000, immutable"

          aws s3 cp "mkosi.output/$ISO.sha256.txt" "s3://$R2_BUCKET_INSTALLER/$ISO.sha256.txt" \
            --content-type "text/plain" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Checksum Extensions
        run: just checksum-ext

      - name: Sign and upload extensions to Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          set -euo pipefail

          R2_BUCKET_UPDATES="${{inputs.build_type}}-updates"

          # Matches Path=.../%a/ext in ext-*.transfer
          for f in mkosi.output/ext/ext-*.raw.zst; do
            aws s3 cp "$f" "s3://$R2_BUCKET_UPDATES/$ARCH/ext/" \
              --cache-control "public, max-age=31536000, immutable"
          done

          # Send the current SHA as versioned SHA to the bucket
          aws s3 cp mkosi.output/ext/SHA256SUMS \
            "s3://$R2_BUCKET_UPDATES/$ARCH/ext/SHA256SUMS_versioned.$TIMESTAMP" \
            --content-type "text/plain" \
            --cache-control "no-cache"

          TEMP_EXT_SHAS="temp_shas_ext"
          mkdir -p "$TEMP_EXT_SHAS"

          # Download all versioned SHA, including the one generated at last step
          aws s3 cp "s3://$R2_BUCKET_UPDATES/$ARCH/ext/" "$TEMP_EXT_SHAS/" \
              --recursive \
              --exclude "*" \
              --include "SHA256SUMS_versioned.*"

          # Concatenate all versioned SHA to a master SHA256SUMS, required by sysupdate
          cat ./temp_shas/ext/SHA256SUMS_versioned.* > /temp_shas/ext/SHA256SUMS

          # Sign master ext SHA
          gpg --batch --pinentry-mode loopback \
                --passphrase "${{ secrets.SYSUPDATE_GPG_PASS }}" \
                --local-user "sysupdate" \
                --output "$TEMP_EXT_SHAS/SHA256SUMS.gpg" \
                --detach-sign "$TEMP_EXT_SHAS/SHA256SUMS"

          # Replace master ext SHA in bucket
          aws s3 cp "$TEMP_EXT_SHAS/SHA256SUMS" \
              "s3://$R2_BUCKET_UPDATES/$ARCH/ext/SHA256SUMS" \
              --content-type "text/plain" \
              --cache-control "no-cache"

          # Replace master signed SHA in bucket
          aws s3 cp "$TEMP_EXT_SHAS/SHA256SUMS.gpg" \
              "s3://$R2_BUCKET_UPDATES/$ARCH/ext/SHA256SUMS.gpg" \
              --content-type "application/pgp-signature" \
              --cache-control "no-cache"
