name: Daily OS 9

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build-release.yml
    with:
      stream: daily
    secrets: inherit
