name: daily-distinst

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Debian style build scripts
      uses: actions/checkout@v1
      with:
        ref: debian-live-build

    - name: Build and Upload daily .iso
      run: |
        mkdir artifacts
        docker run --privileged -i \
            -v /proc:/proc \
            -v ${PWD}/artifacts:/artifacts \
            -v ${PWD}:/working_dir \
            -w /working_dir \
            debian:latest \
            /bin/bash -s etc/terraform-juno-daily-distinst-azure.conf "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}" < workflows.sh
