name: distinst-weekly

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v1

    - name: Build and upload distinst .iso
      run: |
        ./workflows.sh etc/terraform-daily-5.1-distinst-azure.conf "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}"
