name: daily

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Upload daily .iso
      run: |
        mkdir artifacts
        docker run --privileged -i \
            -v /proc:/proc \
            -v /artifacts:/artifacts \
            -v ${PWD}:/working_dir \
            -w /working_dir \
            debian:latest \
            /bin/bash -s etc/terraform-juno-daily-azure.conf "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}" < workflow.sh
