name: Build and Release (elementary OS 9)

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build Image and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v8

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install just podman -y

      - name: Generate key
        run: just genkey

      - name: Release
        run: just do-release

      - name: Fix output dir ownership
        run: |
          sudo chown -R "$(id -u):$(id -g)" mkosi.output
          sudo chmod -R u+rwX mkosi.output

      - name: Compress (xz) usr partition
        run: |
          find mkosi.output/sysupdate -maxdepth 1 -type f -name "*.usr-*.raw" ! -name "*verity*" -exec xz -7v -T0 {} +

      - name: Generate SHA256SUMS (all partitions)
        run: |
          cd mkosi.output
          sha256sum *.esp.raw \
              *.usr-*.*.raw.xz \
              *.usr-*-verity.*.raw \
              *.usr-*-verity-sig.*.raw \
              > SHA256SUMS
          cat SHA256SUMS

      - name: Extract Date
        id: get_date
        run: |
          FILE_PATH=$(ls mkosi.output/elementary_*.raw | grep -E 'elementary_[0-9]+\.raw$' | head -n 1)
          TIMESTAMP=$(basename "$FILE_PATH" | sed 's/^elementary_//;s/\..*//')
          echo "RELEASE_TAG=os9-$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "RELEASE_DATE=${TIMESTAMP:0:8}" >> "$GITHUB_OUTPUT"

      - name: Upload usr, iso and SHA256SUMS to Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          aws s3 sync mkosi.output/ "s3://${{ secrets.R2_BUCKET_DAILY_UPDATES }}/" \
            --exclude "*" \
            --include=*.esp.raw \
            --include=*.usr-*.*.raw.xz \
            --include=*.usr-*-verity.*.raw \
            --include=*.usr-*-verity-sig.*.raw \
            --include="SHA256SUMS"
          aws s3 cp mkosi.output/elementaryos-9.0-*.iso "s3://${{ secrets.R2_BUCKET_DAILY_INSTALLER }}/amd64/elementaryos-9.0-daily-amd64.${{ steps.get_date.outputs.RELEASE_DATE }}.iso"

