name: Build and Release Stable (elementary OS 9)

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-release.yml
    with:
      build_type: stable
    secrets: inherit
