#nvidia-addon
[Config]
Dependencies=base

[Output]
ImageId=driver-nvidia-addon
Format=addon
Overlay=yes
Output=driver-nvidia-addon-%a_%v
OutputExtension=addon.efi
CompressOutput=zstd

[Validation]
Verity=yes

[Content]
BaseTrees=%O/base_%v
Packages=systemd-boot-efi
KernelCommandLine=nvidia-drm.modeset=1 module_blacklist=nouveau
